# Generated by Django 5.0.6 on 2024-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('materia', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
            ],
        ),
    ]
